import type { PermissionSet } from "../src/common.js";

export const HASH = `sha256:${"0".repeat(64)}`;

export const NO_PERMISSIONS: PermissionSet = {
  repository: { read: [], write: [], delete: [] },
  shell: { inspect: false, executeAllowlist: [] },
  runtime: { inspect: [], restart: [] },
  browser: { inspect: false, mutateState: false },
  network: { readDomains: [], externalWrite: false },
  subagents: { spawn: false, maximumChildren: 0, maximumDepth: 0 },
};

export const READ_PERMISSIONS: PermissionSet = {
  ...NO_PERMISSIONS,
  repository: { read: ["**"], write: [], delete: [] },
  shell: { inspect: true, executeAllowlist: [] },
  runtime: { inspect: ["local"], restart: [] },
  browser: { inspect: true, mutateState: false },
};

export const VALID_ARTIFACT_BODIES = {
  RunEnvelope: {
    schemaVersion: "1.0",
    runId: "run-01",
    createdAt: "2026-07-15T10:00:00Z",
    originalRequestRef: "artifact://run-01/user-message-01",
    followupRequestRefs: [],
    requestedMode: "analyze_only",
    status: "active",
    workingContext: {
      repositoryRoot: "/workspace/example",
      activeFiles: [],
      applicableRuleRefs: ["repo://AGENTS.md"],
    },
    host: {
      name: "codex",
      version: "0.144.2",
      nativeSubagents: "available",
      capabilities: ["repository.read"],
    },
    authorization: { granted: READ_PERMISSIONS, denied: NO_PERMISSIONS },
    budgets: {
      promptRevisions: 1,
      postExecutionRemediations: 1,
      maximumParallelWorkers: 3,
      maximumSubagentDepth: 1,
    },
    policyRefs: ["repo://AGENTS.md"],
  },
  ContextManifest: {
    schemaVersion: "1.0",
    id: "context-01",
    runId: "run-01",
    repositoryFingerprint: { headCommit: null, dirtyWorktreeHash: HASH },
    pinnedRefs: ["artifact://run-01/user-message-01", "repo://AGENTS.md"],
    candidates: [
      {
        id: "candidate-01",
        ref: "repo://apps/web/src/api.ts",
        locations: ["getProjects"],
        contentHash: HASH,
        byteSize: 120,
        decision: "selected",
        selectionReason: "Defines the request path named by the symptom.",
        path: "apps/web/src/api.ts",
        score: 500,
        pinned: false,
      },
      {
        id: "candidate-02",
        ref: "repo://docs/unrelated.md",
        locations: [],
        contentHash: HASH,
        byteSize: 80,
        decision: "excluded",
        exclusionReason: "Does not affect the reported request boundary.",
      },
    ],
    derivedRefs: [],
    excludedCandidateSummaries: [{ reason: "duplicate_content", count: 1 }],
    inventorySource: "git",
    warnings: [],
    budget: {
      maximumFiles: 20,
      maximumFileBytes: 65_536,
      maximumTotalBytes: 4_096,
      maximumInventoryFiles: 5_000,
      candidateFiles: 2,
      selectedFiles: 1,
      estimatedTokens: 30,
      selectedBytes: 120,
    },
  },
  NextAction: {
    schemaVersion: "1.0",
    id: "action-01",
    runId: "run-01",
    createdAt: "2026-07-15T10:00:01Z",
    rationaleSummary: "The grounded context is sufficient for intent framing.",
    kind: "phase",
    phase: "agent_1_frame",
    logicalRole: "scenario_author",
    instructionRef: "artifact://system/roles/scenario-author-v1",
    inputRefs: ["artifact://run-01/user-message-01"],
    contextManifestRef: "artifact://run-01/context-01",
    requiredOutputType: "ProblemFrame",
    requiredOutputSchema: { type: "object" },
    additionalOutputSchemas: {},
    workNodeId: null,
    effectivePermissions: READ_PERMISSIONS,
    remainingBudgets: {
      promptRevisions: 1,
      postExecutionRemediations: 1,
      remainingPlanToolCalls: 4_000,
      maximumParallelWorkers: 3,
      maximumSubagentDepth: 1,
    },
    stopConditions: ["Do not execute or mutate project state."],
  },
  ClarificationRequest: {
    schemaVersion: "1.0",
    id: "clarification-01",
    runId: "run-01",
    question: "Which account should receive the externally visible change?",
    reason: "user_owned_materially_divergent",
    divergence: "Different answers change the external recipient.",
    evidenceInspected: ["repo://config/accounts.json"],
    blockedBoundary: "network.externalWrite",
    responseConstraints: "One account identifier, or cancel the action.",
    responseChoices: [
      {
        id: "local-only",
        label: "Local only",
        consequence: "Continue without any externally visible action.",
        authorityEffect: "within_current_authority",
        runEffect: "resume",
      },
      {
        id: "cancel",
        label: "Cancel",
        consequence: "Stop the current run without changing project state.",
        authorityEffect: "within_current_authority",
        runEffect: "cancel",
      },
    ],
    permissionExpansionRequired: false,
    rationaleSummary: "The repository cannot determine a user-owned recipient.",
  },
  ProblemFrame: {
    schemaVersion: "1.0",
    id: "frame-01",
    runId: "run-01",
    originalRequestRef: "artifact://run-01/user-message-01",
    intentMode: "analyze_only",
    goal: "Identify why the React client cannot retrieve project data.",
    knownFacts: [
      {
        id: "fact-01",
        claim: "The dashboard remains offline after loading.",
        provenance: "user",
        sourceRef: "artifact://run-01/user-message-01",
      },
    ],
    inferences: [],
    unknowns: [],
    scope: { include: ["apps/web", "apps/api"], exclude: ["production"] },
    constraints: ["Do not mutate project state."],
    nonGoals: ["Do not implement a fix."],
    applicableRuleRefs: ["repo://AGENTS.md"],
    draftAcceptanceCriteria: [
      {
        id: "AC-1",
        stage: "completion",
        requirement: "Identify the failed communication boundary.",
        evidenceRequired: ["runtime_or_browser_evidence"],
      },
    ],
    clarification: { required: false, reason: null },
    rationaleSummary:
      "The request and repository evidence identify a bounded diagnosis.",
  },
  ScenarioSpec: {
    schemaVersion: "1.0",
    id: "scenario-01",
    runId: "run-01",
    problemFrameRef: "artifact://run-01/frame-01",
    title: "Frontend-to-API communication failure",
    narrative: "The dashboard renders but project data does not appear.",
    actor: "Developer investigating a local monorepo",
    observableSymptoms: ["The dashboard reports an offline state."],
    desiredOutcome: "An evidence-backed diagnosis.",
    sourceMap: [
      {
        field: "observableSymptoms[0]",
        sourceRefs: ["artifact://run-01/user-message-01"],
      },
    ],
    promptReadinessRubricRef: "artifact://system/rubrics/contract-readiness-v1",
    rationaleSummary:
      "The scenario is a sourced presentation of the problem frame.",
  },
  TaskContract: {
    schemaVersion: "1.0",
    id: "contract-01",
    runId: "run-01",
    version: 1,
    originalRequestRef: "artifact://run-01/user-message-01",
    problemFrameRef: "artifact://run-01/frame-01",
    intentMode: "analyze_only",
    objective:
      "Identify the failed communication boundary and supported cause.",
    scope: { include: ["apps/web", "apps/api"], exclude: ["production"] },
    constraints: ["Do not mutate project state."],
    nonGoals: ["Do not implement a fix."],
    contextRefs: ["repo://apps/web/src/api.ts"],
    ruleRefs: ["repo://AGENTS.md"],
    permissions: READ_PERMISSIONS,
    acceptanceCriteria: [
      {
        id: "AC-1",
        stage: "completion",
        requirement: "Identify the failed communication boundary.",
        evidenceRequired: ["runtime_or_browser_evidence"],
      },
    ],
    requiredOutputs: ["Evidence-backed diagnosis"],
    verificationRequirements: [
      {
        id: "VR-1",
        stage: "completion",
        description:
          "Capture the failed request or equivalent runtime evidence.",
        required: true,
        capability: "browser.inspect",
        fallback: "Use API logs if browser inspection is unavailable.",
      },
    ],
    stopConditions: ["Stop before any mutation."],
    assumptions: [],
    unresolvedQuestions: [],
    rationaleSummary: "The contract preserves analysis-only authorization.",
  },
  PromptReview: {
    schemaVersion: "1.0",
    id: "prompt-review-01",
    runId: "run-01",
    targetRef: "artifact://run-01/contract-01",
    rubricId: "contract-readiness-v1",
    revisionNumber: 0,
    coverage: [
      {
        sourceRef: "artifact://run-01/user-message-01",
        contractFields: ["objective", "intentMode"],
        status: "covered",
      },
      {
        sourceRef: "artifact://run-01/frame-01",
        contractFields: [
          "scope",
          "constraints",
          "nonGoals",
          "acceptanceCriteria",
          "ruleRefs",
        ],
        status: "covered",
      },
      {
        sourceRef: "artifact://run-01/contract-01",
        contractFields: [
          "permissions",
          "contextRefs",
          "requiredOutputs",
          "verificationRequirements",
          "stopConditions",
          "assumptions",
          "unresolvedQuestions",
        ],
        status: "covered",
      },
    ],
    dimensionScores: {
      intentFidelity: 100,
      repositoryGrounding: 95,
      constraintsAndPermissions: 100,
      testableAcceptance: 95,
      executionFeasibility: 90,
      contextEfficiency: 90,
    },
    overallScore: 96.5,
    hardGates: [
      {
        id: "HG-intent",
        passed: true,
        description: "The objective preserves the user request.",
        evidenceRefs: ["artifact://run-01/user-message-01"],
        rationaleSummary:
          "The objective maps directly to the requested diagnosis.",
      },
    ],
    findings: [],
    decision: "pass",
    rationaleSummary: "The contract is grounded, safe, and testable.",
  },
  WorkPlan: {
    schemaVersion: "1.0",
    id: "plan-01",
    runId: "run-01",
    taskContractRef: "artifact://run-01/contract-01",
    executionMode: "serial",
    nodes: [
      {
        id: "investigate",
        logicalRole: "executor.runtime-investigator",
        objective: "Capture and diagnose the failed request boundary.",
        dependsOn: [],
        inputRefs: ["artifact://run-01/contract-01"],
        contextRefs: ["repo://apps/web/src/api.ts"],
        allowedTools: ["browser.inspect", "repository.read"],
        requiredCapabilities: ["browser.inspect"],
        permissions: READ_PERMISSIONS,
        outputType: "WorkResult",
        acceptanceCriteria: ["AC-1"],
        stopConditions: ["Stop before mutation."],
        budgets: { maximumToolCalls: 12, maximumChildren: 0 },
      },
    ],
    joinRules: [],
    globalBudgets: {
      maximumToolCalls: 12,
      maximumParallelWorkers: 1,
      maximumSubagentDepth: 0,
    },
    planValidation: "valid",
    rationaleSummary:
      "One serial investigation is sufficient for the bounded diagnosis.",
  },
  WorkResult: {
    schemaVersion: "1.0",
    id: "result-01",
    runId: "run-01",
    workPlanRef: "artifact://run-01/plan-01",
    nodeId: "investigate",
    status: "completed",
    observations: [
      {
        id: "claim-01",
        text: "The API rejected the browser origin during preflight.",
        status: "observed",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        confidence: 1,
      },
    ],
    inferences: [
      {
        id: "claim-02",
        text: "The configured origin allowlist is the supported cause.",
        status: "inferred",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        confidence: 0.95,
      },
    ],
    actions: [
      {
        id: "action-01",
        capability: "browser.inspect",
        target: "http://localhost:3000",
        mutating: false,
        status: "completed",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary:
          "Network inspection captures the failed boundary directly.",
      },
    ],
    filesChanged: [],
    toolEventRefs: [],
    evidenceRefs: ["artifact://run-01/browser-response-01"],
    testResults: [],
    acceptanceCoverage: [
      {
        criterionId: "AC-1",
        status: "pass",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary:
          "The response identifies the failing preflight boundary.",
      },
    ],
    unresolvedIssues: [],
    deviations: [],
    rationaleSummary: "The bounded read-only investigation satisfied AC-1.",
  },
  QualityReview: {
    schemaVersion: "1.0",
    id: "quality-review-01",
    runId: "run-01",
    taskContractRef: "artifact://run-01/contract-01",
    workPlanRefs: ["artifact://run-01/plan-01"],
    workResultRefs: ["artifact://run-01/result-01"],
    rubricId: "execution-quality-v1",
    acceptanceResults: [
      {
        criterionId: "AC-1",
        status: "pass",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary:
          "Direct runtime evidence identifies the failed boundary.",
      },
    ],
    ruleCompliance: [
      {
        id: "rule-01",
        subjectRef: "repo://AGENTS.md",
        description: "The run made no project mutation.",
        status: "pass",
        evidenceRefs: ["artifact://run-01/action-ledger-01"],
        rationaleSummary: "Every recorded action is read-only.",
      },
    ],
    regressionChecks: [],
    verificationResults: [
      {
        requirementId: "VR-1",
        capability: "browser.inspect",
        status: "pass",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary:
          "Direct browser evidence satisfies the required verification.",
      },
    ],
    findings: [],
    hardGates: [
      {
        id: "HG-acceptance",
        passed: true,
        description: "Required acceptance criteria have evidence.",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary: "AC-1 has direct runtime evidence.",
      },
    ],
    score: 96,
    remainingRemediations: 1,
    decision: "pass",
    diagnosisGate: null,
    remediationWorkOrder: null,
    rationaleSummary: "Execution is within scope and evidence-backed.",
  },
  ReleaseAudit: {
    schemaVersion: "1.0",
    id: "release-audit-01",
    runId: "run-01",
    originalRequestRef: "artifact://run-01/user-message-01",
    taskContractRef: "artifact://run-01/contract-01",
    workPlanRefs: ["artifact://run-01/plan-01"],
    workResultRefs: ["artifact://run-01/result-01"],
    qualityReviewRef: "artifact://run-01/quality-review-01",
    userFidelity: [
      {
        id: "fidelity-01",
        subjectRef: "artifact://run-01/user-message-01",
        description: "The result answers the requested diagnosis.",
        status: "pass",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary:
          "The directly captured result resolves the requested boundary.",
      },
    ],
    modeCompliance: "pass",
    claimEvidenceMatrix: [
      {
        claimId: "claim-01",
        claim: "The request fails at CORS preflight.",
        criterionIds: ["AC-1"],
        basis: "direct",
        status: "supported",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        rationaleSummary:
          "The captured browser response shows the failed preflight.",
      },
    ],
    unresolvedRisks: [],
    findings: [],
    remainingRemediations: 1,
    decision: "release",
    remediationDefect: null,
    userReportRef: "artifact://run-01/user-report-01",
    rationaleSummary: "The report is faithful, compliant, and fully supported.",
  },
  UserReport: {
    schemaVersion: "1.0",
    id: "user-report-01",
    runId: "run-01",
    terminalStatus: "completed",
    summary:
      "The request fails at CORS preflight because the local origin is not allowed.",
    completionClaims: [
      {
        id: "claim-01",
        text: "The request fails at CORS preflight.",
        status: "observed",
        evidenceRefs: ["artifact://run-01/browser-response-01"],
        confidence: 1,
      },
    ],
    findingRefs: ["artifact://run-01/result-01"],
    changeRefs: [],
    verificationRefs: ["artifact://run-01/browser-response-01"],
    unresolvedRisks: [],
    permissionsHonored: true,
    nextActions: [
      {
        id: "next-01",
        description:
          "Authorize a separate fix run to update the local origin allowlist.",
        requiresAuthorization: true,
      },
    ],
    traceRef: "trace://run-01",
    rationaleSummary:
      "The report states the supported cause without claiming a fix.",
  },
  TraceEvent: {
    schemaVersion: "1.0",
    id: "event-0042",
    runId: "run-01",
    sequence: 42,
    timestamp: "2026-07-15T10:05:00Z",
    actor: "quality_controller",
    phase: "agent_3_quality_review",
    eventType: "phase_submitted",
    inputRefs: ["artifact://run-01/result-01"],
    outputRefs: ["artifact://run-01/quality-review-01"],
    tool: null,
    permissionDecision: null,
    budgetSnapshot: {
      promptRevisions: 1,
      postExecutionRemediations: 1,
      transportRetries: 0,
    },
    rationaleSummary: "All acceptance criteria have direct evidence.",
    redactions: [],
  },
} as const;
